### ISSUE TITLE
Suggestion: Submit to Fyne apps!

### ISSUE THREAD

**Issue by mevdschee** [zquestz/fortunate#1]
Please consider submitting your app to Fyne Apps. IMHO Fortunate is a nice app and submitting helps show others what great things you can do with Fyne.

See: https://docs.fyne.io/submit/

**Comment by andydotxyz** [comment]
It looks like the request was already in the pipe... https://apps.fyne.io/apps/at.greyh.fortunate.html

**Comment by zquestz** [comment]
Yep it was just listed today!

**Comment by mevdschee** [comment]
Congratulations, what a great addition. Thank you for making and sharing Fortunate, it's inspriring!

**Comment by zquestz** [comment]
Any idea how to update an existing app entry? I added macOS support and would love that reflected in the listing.

**Comment by mevdschee** [comment]
>Any idea how to update an existing app entry? 

No, I would submit the same app again with updated details.

**Comment by andydotxyz** [comment]
Or just ping me and I can update the entry :) (done!)
